name: Publish Docs to GitHub Pages

on:
  push:
    branches:
      - release  # Only trigger on the release branch

permissions:
  contents: read
  pages: write  # Required for GitHub Pages API
  id-token: write  # Required for authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      # Step to dynamically generate the .config file with the secret
      - name: Generate .config file
        run: |
          echo "[codegreen]" > docs/.codegreencore.config
          echo "ENTSOE_token=${{ secrets.ENTSOE_TOKEN }}" >> docs/.codegreencore.config
          echo "enable_energy_caching=false" >> docs/.codegreencore.config
      - name: Verify .config file
        run: |
          cat docs/.codegreencore.config
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  .
          pip install sphinx==7.4.7  # Install Sphinx and theme if needed

      - name: Build Sphinx Docs
        run: |
          make html  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./build/html  # Ensure this is the correct path

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # The URL for your GitHub Pages site

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2