name: Publish Package and Docs

on:
  push:
    branches:
      - release  # Trigger this workflow when a push occurs on the "release" branch

jobs:
  build_docs:
    name: Build and Publish Docs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx_rtd_theme  # Install Sphinx and theme if needed

      - name: Build Sphinx Docs
        run: |
          cd docs
          make html  # Assuming docs are configured to build HTML files

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html  # Location of the built HTML files

  # publish_pypi:
  #   name: Publish to PyPI
  #   runs-on: ubuntu-latest
  #   needs: build_docs  # Only run this job after docs are built and published

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.x'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install build twine  # Install build and twine for publishing

  #     - name: Build the package
  #       run: |
  #         python -m build

  #     - name: Publish to PyPI
  #       env:
  #         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  #         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  #       run: |
  #         python -m twine upload dist/*  # Upload the package to PyPI
